// Autogenerated from runtime/logs/displayable.i

package ideal.runtime.logs;

import ideal.library.elements.*;
import ideal.library.texts.*;
import ideal.library.messages.*;
import ideal.runtime.elements.*;
import ideal.runtime.texts.*;

public interface any_displayable extends any_value { }
