// Autogenerated from runtime/resources/resource_store.i

package ideal.runtime.resources;

import ideal.library.elements.*;
import ideal.library.resources.*;
import ideal.runtime.elements.*;

public interface immutable_resource_store extends immutable_value, readonly_resource_store { }
