// Autogenerated from isource/runtime/resources/resource_store.i

package ideal.runtime.resources;

import ideal.library.elements.*;
import ideal.library.resources.*;
import ideal.runtime.elements.*;

public interface writeonly_resource_store extends any_resource_store { }
