// Autogenerated from development/modifiers/access_modifier.i

package ideal.development.modifiers;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;

public class access_modifier extends base_modifier_kind {
  public static final access_modifier public_modifier = new access_modifier(new base_string("public"));
  public static final access_modifier private_modifier = new access_modifier(new base_string("private"));
  public static final access_modifier protected_modifier = new access_modifier(new base_string("protected"));
  public static final access_modifier local_modifier = new access_modifier(new base_string("local"));
  private access_modifier(final string name) {
    super(name);
  }
}
