// Autogenerated from development/modifiers/base_modifier_kind.i

package ideal.development.modifiers;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;

public class base_modifier_kind extends debuggable implements modifier_kind, readonly_displayable {
  private final simple_name the_name;
  public base_modifier_kind(final string name) {
    this.the_name = simple_name.make(name);
  }
  public @Override simple_name name() {
    return this.the_name;
  }
  public @Override string to_string() {
    return name_utilities.in_brackets(this.the_name);
  }
  public @Override string display() {
    return this.to_string();
  }
}
