// Autogenerated from development/types/concrete_type_action.i

package ideal.development.types;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.flavors.*;
import ideal.development.declarations.*;
import ideal.development.kinds.*;

public class concrete_type_action extends type_action {
  private final type the_type;
  public concrete_type_action(final type the_type, final origin the_origin) {
    super(the_origin);
    assert the_type != null;
    this.the_type = the_type;
  }
  public @Override type get_type() {
    return this.the_type;
  }
}
