// Autogenerated from development/types/type_declaration_context.i

package ideal.development.types;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.flavors.*;
import ideal.development.declarations.*;
import ideal.development.kinds.*;
import ideal.library.graphs.*;

public interface writeonly_type_declaration_context extends writeonly_value, any_type_declaration_context { }
