// Autogenerated from development/literals/integer_literal.i

package ideal.development.literals;

import ideal.library.elements.*;
import ideal.library.characters.*;
import ideal.runtime.elements.*;
import ideal.runtime.characters.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.machine.channels.string_writer;

public class integer_literal extends debuggable implements literal<Integer> {
  private final Integer integer_value;
  private final string image;
  public final Integer radix;
  public integer_literal(final Integer integer_value, final string image, final Integer radix) {
    this.integer_value = integer_value;
    this.image = image;
    this.radix = radix;
  }
  public integer_literal(final Integer integer_value) {
    this(integer_value, utilities.string_of(integer_value), radixes.DEFAULT_RADIX);
  }
  public @Override Integer the_value() {
    return this.integer_value;
  }
  public @Override string to_string() {
    return this.image;
  }
}
