// Autogenerated from development/literals/literal_fragment.i

package ideal.development.literals;

import ideal.library.elements.*;
import ideal.library.characters.*;
import ideal.runtime.elements.*;
import ideal.runtime.characters.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.machine.channels.string_writer;

public abstract class literal_fragment extends debuggable implements deeply_immutable_data, stringable {
  public literal_fragment() { }
}
