// Autogenerated from development/names/cast_type.i

package ideal.development.names;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.symbols.base_symbols;

public class cast_type extends operator {
  protected cast_type(final token_type name, final string alpha_name) {
    super(operator_type.INFIX, name, alpha_name, precedence.RELATIONAL);
  }
}
