// Autogenerated from development/names/keywords.i

package ideal.development.names;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.symbols.base_symbols;

public class keywords {
  public static final keyword RESERVED = new keyword(new base_string("reserved"));
  public static final keyword THIS = new keyword(new base_string("this"));
  public static final keyword SUPER = new keyword(new base_string("super"));
  public static final keyword NEW = new keyword(new base_string("new"));
  public static final keyword OR = new keyword(new base_string("or"), base_symbols.OR);
  public static final keyword IS = new keyword(new base_string("is"), base_symbols.IS);
  public static final keyword IS_NOT = new keyword(new base_string("is_not"), base_symbols.IS_NOT);
  public static final keyword ASSERT = new keyword(new base_string("assert"), base_symbols.ASSERT);
  public static final keyword RETURN = new keyword(new base_string("return"), base_symbols.RETURN);
  public static final keyword IF = new keyword(new base_string("if"), base_symbols.IF);
  public static final keyword ELSE = new keyword(new base_string("else"), base_symbols.ELSE);
  public static final keyword LOOP = new keyword(new base_string("loop"), base_symbols.LOOP);
  public static final keyword WHILE = new keyword(new base_string("while"), base_symbols.WHILE);
  public static final keyword FOR = new keyword(new base_string("for"), base_symbols.FOR);
  public static final keyword IMPORT = new keyword(new base_string("import"), base_symbols.IMPORT);
  public static final keyword USE = new keyword(new base_string("use"), base_symbols.USE);
  public static final keyword TARGET = new keyword(new base_string("target"), base_symbols.TARGET);
  public static final keyword PLEASE = new keyword(new base_string("please"), base_symbols.PLEASE);
}
