// Autogenerated from development/names/operator_type.i

package ideal.development.names;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.symbols.base_symbols;

public class operator_type extends debuggable implements identifier, readonly_displayable {
  public final string name;
  public final Integer arity;
  private operator_type(final string name, final Integer arity) {
    this.name = name;
    this.arity = arity;
  }
  public @Override string to_string() {
    return this.name;
  }
  public @Override string display() {
    return this.to_string();
  }
  public static final operator_type PREFIX = new operator_type(new base_string("prefix"), 1);
  public static final operator_type POSTFIX = new operator_type(new base_string("postfix"), 1);
  public static final operator_type INFIX = new operator_type(new base_string("infix"), 2);
}
