// Autogenerated from development/names/quote_type.i

package ideal.development.names;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.symbols.base_symbols;

public class quote_type extends punctuation_type {
  public quote_type(final string name) {
    super(name);
  }
}
