// Autogenerated from development/values/base_string_value.i

package ideal.development.values;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.reflections.*;
import ideal.development.elements.*;
import ideal.development.origins.*;
import ideal.development.names.*;
import ideal.development.flavors.*;
import ideal.development.declarations.*;
import ideal.development.kinds.*;
import ideal.development.types.*;
import ideal.development.jumps.*;
import ideal.development.notifications.*;
import ideal.development.flags.*;

public class base_string_value extends base_constant_value<string> implements string_value {
  public base_string_value(final string value, final type bound) {
    super(value, bound);
  }
  public @Override string constant_to_string() {
    return ((string_value) this).unwrap();
  }
}
