// Autogenerated from development/values/base_constant_value.i

package ideal.development.values;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.reflections.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.flavors.*;
import ideal.development.declarations.*;
import ideal.development.kinds.*;
import ideal.development.types.*;
import ideal.development.jumps.*;
import ideal.development.notifications.*;
import ideal.development.flags.*;

public abstract class base_constant_value<value_type> extends base_data_value {
  private final value_type boxed;
  public base_constant_value(final value_type boxed, final type bound) {
    super(bound);
    assert !ideal.machine.elements.runtime_util.values_equal(boxed, null);
    this.boxed = boxed;
  }
  public @Override value_type unwrap() {
    return this.boxed;
  }
  public abstract string constant_to_string();
  public @Override string to_string() {
    return utilities.describe(this, this.constant_to_string());
  }
}
