// Autogenerated from development/values/list_context.i

package ideal.development.values;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.reflections.*;
import ideal.development.elements.*;
import ideal.development.origins.*;
import ideal.development.names.*;
import ideal.development.flavors.*;
import ideal.development.declarations.*;
import ideal.development.kinds.*;
import ideal.development.types.*;
import ideal.development.jumps.*;
import ideal.development.notifications.*;
import ideal.development.flags.*;

public class list_context implements variable_context {
  private final readonly_list<Object> the_list;
  public list_context(final readonly_list<Object> the_list) {
    this.the_list = the_list;
  }
  public @Override void put_var(final variable_id key, final value_wrapper value) {
    utilities.panic(ideal.machine.elements.runtime_util.concatenate(new base_string("list_context.put_var() for "), key));
  }
  public @Override value_wrapper get_var(final variable_id key) {
    if (key.short_name() == common_names.size_name) {
      return new integer_value(this.the_list.size(), common_types.immutable_nonnegative_type());
    }
    {
      utilities.panic(ideal.machine.elements.runtime_util.concatenate(new base_string("list_context.get_var() for "), key));
      return null;
    }
  }
}
