// Autogenerated from development/declarations/annotation_set.i

package ideal.development.declarations;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.futures.*;
import ideal.development.names.*;
import ideal.development.comments.*;
import ideal.development.modifiers.*;

import javax.annotation.Nullable;

public interface annotation_set extends immutable_data {
  access_modifier access_level();
  boolean has(modifier_kind the_kind);
  @Nullable documentation the_documentation();
  immutable_list<origin> origins();
}
