// Autogenerated from development/declarations/type_parameter_declaration.i

package ideal.development.declarations;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.comments.*;
import ideal.development.modifiers.*;
import ideal.development.comments.documentation;

public interface deeply_immutable_type_parameter_declaration extends deeply_immutable_type_declaration, immutable_type_parameter_declaration { }
