// Autogenerated from development/declarations/annotation_set.i

package ideal.development.declarations;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.comments.*;
import ideal.development.modifiers.*;
import ideal.development.comments.documentation;

public interface immutable_annotation_set extends immutable_analyzable, immutable_analysis_result, immutable_data, readonly_annotation_set { }
