// Autogenerated from development/declarations/type_parameter_declaration.i

package ideal.development.declarations;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.comments.*;
import ideal.development.modifiers.*;

import javax.annotation.Nullable;

public interface readonly_type_parameter_declaration extends readonly_type_declaration, any_type_parameter_declaration {
  type variable_type();
  @Nullable analyzable get_type_analyzable();
}
