// Autogenerated from development/declarations/variable_declaration.i

package ideal.development.declarations;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.comments.*;
import ideal.development.modifiers.*;
import ideal.development.comments.documentation;

import javax.annotation.Nullable;

public interface readonly_variable_declaration extends readonly_named_declaration, readonly_variable_id, any_variable_declaration {
  variable_category get_category();
  annotation_set annotations();
  action_name short_name();
  principal_type declared_in_type();
  type_flavor get_flavor();
  type value_type();
  type reference_type();
  boolean declared_as_reference();
  readonly_list<declaration> get_overriden();
  @Nullable action init_action();
}
