// Autogenerated from development/declarations/type_announcement.i

package ideal.development.declarations;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.comments.*;
import ideal.development.modifiers.*;

public interface type_announcement extends type_declaration, readonly_type_announcement, writeonly_type_announcement {
  void load_type();
}
