// Autogenerated from runtime/elements/has_equivalence.i

package ideal.runtime.elements;

import ideal.library.elements.*;

public interface deeply_immutable_has_equivalence extends deeply_immutable_equality_comparable, immutable_has_equivalence { }
