// Autogenerated from development/scanners/base_scanner_element.i

package ideal.development.scanners;

import ideal.library.elements.*;
import ideal.library.characters.*;
import ideal.runtime.elements.*;
import ideal.runtime.characters.*;
import ideal.runtime.patterns.*;
import ideal.runtime.logs.*;
import ideal.machine.characters.*;
import ideal.machine.channels.string_writer;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.notifications.*;
import ideal.development.origins.*;
import ideal.development.comments.*;
import ideal.development.literals.*;
import ideal.development.modifiers.*;
import ideal.development.constructs.constraint_category;
import ideal.development.jumps.jump_category;

public abstract class base_scanner_element implements scanner_element {
  private scanner_config the_scanner_config;
  public @Override void set_config(final scanner_config the_scanner_config) {
    this.the_scanner_config = the_scanner_config;
  }
  protected scanner_config config() {
    assert this.the_scanner_config != null;
    return this.the_scanner_config;
  }
  protected character_handler the_character_handler() {
    return this.config().the_character_handler();
  }
  public base_scanner_element() { }
}
