// Autogenerated from development/components/transformer.i

package ideal.development.components;

import ideal.library.elements.*;
import ideal.development.elements.*;

public interface deeply_immutable_transformer extends deeply_immutable_value, immutable_transformer { }
