// Autogenerated from development/components/printer.i

package ideal.development.components;

import ideal.library.elements.*;
import ideal.development.elements.*;
import ideal.library.texts.text_fragment;

public interface immutable_printer extends immutable_value, readonly_printer { }
