// Autogenerated from development/notifications/notification_level.i

package ideal.development.notifications;

import ideal.library.elements.*;
import ideal.library.channels.*;
import ideal.library.texts.*;
import ideal.library.messages.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.runtime.texts.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.origins.*;
import ideal.development.types.*;
import ideal.development.jumps.panic_value;

public enum notification_level implements deeply_immutable_data, reference_equality {
  ERROR(log_level.ERROR),
  WARNING(log_level.WARNING),
  INFORMATIONAL(log_level.INFORMATIONAL);
  public final log_level the_log_level;
  private notification_level(final log_level the_log_level) {
    this.the_log_level = the_log_level;
  }
  public string to_string() {
    return new base_string(toString());
  }
}
