// Autogenerated from development/notifications/ok_signal.i

package ideal.development.notifications;

import ideal.library.elements.*;
import ideal.library.channels.*;
import ideal.library.texts.*;
import ideal.library.messages.*;
import ideal.runtime.elements.*;
import ideal.runtime.texts.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.origins.*;

public class ok_signal extends debuggable implements signal {
  public static final ok_signal instance = new ok_signal();
  public @Override origin deeper_origin() {
    return origin_utilities.no_origin;
  }
  public @Override string to_string() {
    return new base_string("ok");
  }
  public ok_signal() { }
}
