// Autogenerated from development/grammars/grammar_scanner.i

package ideal.development.grammars;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.constructs.*;
import ideal.development.scanners.*;

public class grammar_scanner {
  public void register_tokens(final scanner_config the_scanner_config) {
    the_scanner_config.add_punctuation(punctuation.COLON_COLON_EQUALS);
    the_scanner_config.add_keyword(keywords.GRAMMAR);
    the_scanner_config.add_keyword(keywords.TERMINAL);
    the_scanner_config.add_keyword(keywords.NONTERMINAL);
  }
  public grammar_scanner() { }
}
