// Autogenerated from development/constructs/annotation_construct.i

package ideal.development.constructs;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.development.elements.*;
import ideal.development.names.*;

public interface annotation_construct extends construct, readonly_annotation_construct, writeonly_annotation_construct { }
