// Autogenerated from development/constructs/annotation_construct.i

package ideal.development.constructs;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.development.elements.*;
import ideal.development.names.*;

public interface any_annotation_construct extends any_construct { }
