// Autogenerated from development/constructs/annotation_construct.i

package ideal.development.constructs;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.development.elements.*;
import ideal.development.names.*;

public interface deeply_immutable_annotation_construct extends deeply_immutable_construct, immutable_annotation_construct { }
