// Autogenerated from development/constructs/jump_type.i

package ideal.development.constructs;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.development.elements.*;
import ideal.development.names.*;

public enum jump_type implements deeply_immutable_data, stringable {
  BREAK_JUMP(new base_string("break")),
  CONTINUE_JUMP(new base_string("continue"));
  private final string name_string;
  private jump_type(final string name_string) {
    this.name_string = name_string;
  }
  public simple_name jump_name() {
    return simple_name.make(this.name_string);
  }
  public @Override string to_string() {
    return this.name_string;
  }
}
