// Autogenerated from development/constructs/parameter_construct.i

package ideal.development.constructs;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.development.elements.*;
import ideal.development.names.*;

public class parameter_construct extends base_construct {
  public final construct main;
  public final readonly_list<construct> parameters;
  public final grouping_type grouping;
  public parameter_construct(final construct main, final readonly_list<construct> parameters, final grouping_type grouping, final origin generated_origin) {
    super(generated_origin);
    assert main != null;
    this.main = main;
    assert parameters != null;
    this.parameters = parameters;
    assert grouping != null;
    this.grouping = grouping;
  }
  public @Override readonly_list<construct> children() {
    final base_list<construct> generated_result = new base_list<construct>();
    generated_result.append(this.main);
    generated_result.append_all(this.parameters);
    return generated_result;
  }
}
