// Autogenerated from development/constructs/type_declaration_construct.i

package ideal.development.constructs;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.development.elements.*;
import ideal.development.names.*;

import javax.annotation.Nullable;

public class type_declaration_construct extends base_construct {
  public final readonly_list<annotation_construct> annotations;
  public final kind kind;
  public final action_name name;
  public final @Nullable readonly_list<construct> parameters;
  public final readonly_list<construct> body;
  public boolean has_parameters() {
    return this.parameters != null;
  }
  public @Override string to_string() {
    return utilities.describe(this, this.name);
  }
  public type_declaration_construct(final readonly_list<annotation_construct> annotations, final kind kind, final action_name name, final @Nullable readonly_list<construct> parameters, final readonly_list<construct> body, final origin generated_origin) {
    super(generated_origin);
    assert annotations != null;
    this.annotations = annotations;
    assert kind != null;
    this.kind = kind;
    assert name != null;
    this.name = name;
    this.parameters = parameters;
    assert body != null;
    this.body = body;
  }
  public @Override readonly_list<construct> children() {
    final base_list<construct> generated_result = new base_list<construct>();
    generated_result.append_all((readonly_list<construct>) (Object) this.annotations);
    if (this.parameters != null)
      generated_result.append_all((readonly_list<construct>) (Object) this.parameters);
    generated_result.append_all(this.body);
    return generated_result;
  }
}
