// Autogenerated from runtime/channels/auto_sync_output.i

package ideal.runtime.channels;

import ideal.library.elements.*;
import ideal.library.channels.*;
import ideal.runtime.elements.*;

public class auto_sync_output<value_type> implements output<value_type> {
  private final output<value_type> the_output;
  public auto_sync_output(final output<value_type> the_output) {
    this.the_output = the_output;
  }
  public @Override void write(final value_type value) {
    this.the_output.write(value);
    this.the_output.sync();
  }
  public @Override void write_all(final readonly_list<value_type> values) {
    this.the_output.write_all(values);
    this.the_output.sync();
  }
  public @Override void sync() {
    this.the_output.sync();
  }
  public @Override void close() {
    this.the_output.close();
  }
  public @Override void teardown() {
    this.the_output.teardown();
  }
}
