// Autogenerated from runtime/channels/output_counter.i

package ideal.runtime.channels;

import ideal.library.elements.*;
import ideal.library.channels.*;
import ideal.runtime.elements.*;

public class output_counter<value_type> implements output<value_type> {
  private final output<value_type> the_output;
  private Integer count;
  public output_counter(final output<value_type> the_output) {
    this.the_output = the_output;
    this.count = 0;
  }
  public Integer get_count() {
    return this.count;
  }
  public @Override void write(final value_type value) {
    this.count += 1;
    this.the_output.write(value);
  }
  public @Override void write_all(final readonly_list<value_type> values) {
    this.count += values.size();
    this.the_output.write_all(values);
  }
  public @Override void sync() {
    this.the_output.sync();
  }
  public @Override void close() {
    this.the_output.close();
  }
  public @Override void teardown() {
    this.the_output.teardown();
  }
}
