// Autogenerated from development/origins/fragment_origin.i

package ideal.development.origins;

import ideal.library.elements.*;
import ideal.library.texts.*;
import ideal.library.channels.*;
import ideal.library.resources.*;
import ideal.library.patterns.*;
import ideal.runtime.elements.*;
import ideal.runtime.texts.*;
import ideal.runtime.patterns.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;

public class fragment_origin extends debuggable implements deeply_immutable_data, origin {
  public final origin begin;
  public final origin main;
  public final origin end;
  public fragment_origin(final origin begin, final origin main, final origin end) {
    this.begin = begin;
    this.main = main;
    this.end = end;
  }
  public @Override origin deeper_origin() {
    return this.main;
  }
}
