// Autogenerated from development/origins/origin_utilities.i

package ideal.development.origins;

import ideal.library.elements.*;
import ideal.library.texts.*;
import ideal.library.channels.*;
import ideal.library.resources.*;
import ideal.library.patterns.*;
import ideal.runtime.elements.*;
import ideal.runtime.texts.*;
import ideal.runtime.patterns.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;

import javax.annotation.Nullable;

public class origin_utilities {
  public static @Nullable source_content get_source(@Nullable origin the_origin) {
    while (the_origin != null) {
      if (the_origin instanceof source_content) {
        return ((source_content) the_origin);
      }
      the_origin = the_origin.deeper_origin();
    }
    return null;
  }
  public static string get_source_prefix(@Nullable origin the_origin) {
    while (the_origin != null) {
      if (the_origin instanceof text_origin) {
        final source_content source = ((text_origin) the_origin).source;
        final int line_number = source.line_number(((text_origin) the_origin));
        return ideal.machine.elements.runtime_util.concatenate(ideal.machine.elements.runtime_util.concatenate(ideal.machine.elements.runtime_util.concatenate(source.name, new base_string(":")), line_number), new base_string(": "));
      }
      if (the_origin instanceof source_content) {
        return ideal.machine.elements.runtime_util.concatenate(((source_content) the_origin).name, new base_string(": "));
      }
      the_origin = the_origin.deeper_origin();
    }
    return new base_string("");
  }
}
