// Autogenerated from development/origins/special_origin.i

package ideal.development.origins;

import ideal.library.elements.*;
import ideal.library.texts.*;
import ideal.library.channels.*;
import ideal.library.resources.*;
import ideal.library.patterns.*;
import ideal.runtime.elements.*;
import ideal.runtime.texts.*;
import ideal.runtime.patterns.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;

import javax.annotation.Nullable;

public class special_origin extends debuggable implements origin, deeply_immutable_data, stringable {
  public final string description;
  public special_origin(final string description) {
    this.description = description;
  }
  public @Override @Nullable origin deeper_origin() {
    return null;
  }
  public @Override string to_string() {
    return this.description;
  }
}
