// Autogenerated from isource/runtime/texts/base_element.i

package ideal.runtime.texts;

import ideal.library.elements.*;
import ideal.library.texts.*;
import ideal.runtime.elements.*;
import ideal.library.channels.output;

import javax.annotation.Nullable;

public class base_element extends debuggable implements text_element {
  private final element_id id;
  private final immutable_dictionary<attribute_id, string> the_attributes;
  private final @Nullable text_fragment the_children;
  public base_element(final element_id id) {
    this(id, new list_dictionary<attribute_id, string>(), null);
  }
  public base_element(final element_id id, final readonly_dictionary<attribute_id, string> attributes, final @Nullable text_fragment children) {
    this.id = id;
    this.the_attributes = attributes.frozen_copy();
    this.the_children = children;
  }
  public static text_element make(final element_id id, final @Nullable text_fragment children) {
    return new base_element(id, new list_dictionary<attribute_id, string>(), children);
  }
  public static text_element make(final element_id id, final attribute_id attr, final string value, final @Nullable text_fragment children) {
    return new base_element(id, new list_dictionary<attribute_id, string>(attr, value), children);
  }
  public @Override element_id get_id() {
    return id;
  }
  public @Override immutable_dictionary<attribute_id, string> attributes() {
    return the_attributes;
  }
  public @Override @Nullable text_fragment children() {
    return the_children;
  }
  public @Override string to_string() {
    return ideal.machine.elements.runtime_util.concatenate(ideal.machine.elements.runtime_util.concatenate(new base_string("<"), id.to_string()), new base_string(" ...>"));
  }
}
