// Autogenerated from runtime/texts/base_list_text_node.i

package ideal.runtime.texts;

import ideal.library.elements.*;
import ideal.library.texts.*;
import ideal.runtime.elements.*;
import ideal.library.channels.output;

public class base_list_text_node extends debuggable implements list_text_node {
  private final immutable_list<text_node> the_nodes;
  public base_list_text_node(final readonly_list<text_node> the_nodes) {
    this.the_nodes = the_nodes.frozen_copy();
  }
  public static list_text_node make(final text_node first, final text_node second) {
    return new base_list_text_node(new base_immutable_list<text_node>(new ideal.machine.elements.array<text_node>(new text_node[]{ first, second })));
  }
  public static list_text_node make(final text_node first, final text_node second, final text_node third) {
    return new base_list_text_node(new base_immutable_list<text_node>(new ideal.machine.elements.array<text_node>(new text_node[]{ first, second, third })));
  }
  public @Override immutable_list<text_node> nodes() {
    return the_nodes;
  }
  public @Override string to_string() {
    return new base_string("base_list_text_node...");
  }
}
