// Autogenerated from runtime/texts/base_namespace.i

package ideal.runtime.texts;

import ideal.library.elements.*;
import ideal.library.texts.*;
import ideal.runtime.elements.*;
import ideal.library.channels.output;

public class base_namespace extends debuggable implements text_namespace, reference_equality {
  private final string name;
  public base_namespace(final string name) {
    this.name = name;
  }
  public @Override string short_name() {
    return this.name;
  }
  public @Override string to_string() {
    return this.name;
  }
}
