// Autogenerated from runtime/texts/doc_parser.i

package ideal.runtime.texts;

import ideal.library.elements.*;
import ideal.library.characters.*;
import ideal.library.texts.*;
import ideal.runtime.elements.*;
import ideal.library.channels.output;

public class doc_parser extends markup_parser {
  public doc_parser(final doc_grammar grammar, final procedure1<Void, string> error_reporter) {
    super(grammar, error_reporter);
  }
  public text_fragment parse_content(final string text) {
    return ((doc_grammar) this.grammar).parse_content(text, this);
  }
}
