// Autogenerated from runtime/texts/doc_grammar.i

package ideal.runtime.texts;

import ideal.library.elements.*;
import ideal.library.characters.*;
import ideal.library.texts.*;
import ideal.runtime.elements.*;
import ideal.library.channels.output;
import ideal.library.patterns.*;
import ideal.runtime.patterns.*;

public class doc_grammar extends markup_grammar {
  public doc_grammar(final character_handler the_character_handler) {
    super(the_character_handler);
  }
  public @Override void update_matchers() { }
  public text_fragment parse_content(final string text, final doc_parser parser) {
    this.parser = parser;
    return this.content.parse(text);
  }
}
