// Autogenerated from development/elements/action_name.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface action_name extends identifier, deeply_immutable_reference_equality { }
