// Autogenerated from development/elements/origin.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface any_origin extends any_data, any_reference_equality, any_stringable { }
