// Autogenerated from development/elements/declaration.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface any_declaration extends any_analyzable_or_declaration { }
