// Autogenerated from development/elements/position.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface any_position extends any_data, any_reference_equality, any_stringable { }
