// Autogenerated from development/elements/construct.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface construct extends data, origin, readonly_construct, writeonly_construct { }
