// Autogenerated from development/elements/declaration.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface declaration extends origin, readonly_declaration, writeonly_declaration { }
