// Autogenerated from development/elements/execution_context.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface deeply_immutable_execution_context extends deeply_immutable_value, immutable_execution_context { }
