// Autogenerated from development/elements/declaration.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface deeply_immutable_declaration extends deeply_immutable_origin, immutable_declaration { }
