// Autogenerated from development/elements/flavor_profile.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface deeply_immutable_flavor_profile extends deeply_immutable_reference_equality, immutable_flavor_profile { }
