// Autogenerated from development/elements/analyzable.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface deeply_immutable_analyzable extends deeply_immutable_analyzable_or_declaration, immutable_analyzable { }
