// Autogenerated from development/elements/declaration.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface immutable_declaration extends immutable_position, readonly_declaration { }
