// Autogenerated from development/elements/construct.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface immutable_construct extends immutable_data, immutable_position, readonly_construct { }
