// Autogenerated from development/elements/execution_context.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface immutable_execution_context extends immutable_value, readonly_execution_context { }
