// Autogenerated from development/elements/action_context.i

package ideal.development.elements;

import ideal.library.elements.*;
import ideal.library.graphs.graph;

public interface immutable_action_context extends immutable_value, readonly_action_context { }
