// Autogenerated from development/elements/origin.i

package ideal.development.elements;

import ideal.library.elements.*;

import javax.annotation.Nullable;

public interface readonly_origin extends readonly_data, readonly_reference_equality, readonly_stringable, any_origin {
  @Nullable origin deeper_origin();
}
