// Autogenerated from development/elements/position.i

package ideal.development.elements;

import ideal.library.elements.*;

import javax.annotation.Nullable;

public interface readonly_position extends readonly_data, readonly_reference_equality, readonly_stringable, any_position {
  @Nullable position source_position();
}
