// Autogenerated from development/elements/language_settings.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface readonly_language_settings extends any_language_settings { }
