// Autogenerated from development/elements/execution_context.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface readonly_execution_context extends readonly_value, any_execution_context { }
