// Autogenerated from development/elements.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface readonly_position extends readonly_data, readonly_reference_equality, readonly_stringable, any_position {
  position source_position();
}
