// Autogenerated from development/elements/declaration.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface readonly_declaration extends readonly_analyzable, any_declaration {
  principal_type declared_in_type();
  boolean has_errors();
}
