// Autogenerated from development/elements/declaration.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface writeonly_declaration extends writeonly_analyzable, any_declaration { }
