// Autogenerated from development/elements/flavor_profile.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface writeonly_flavor_profile extends writeonly_reference_equality, any_flavor_profile { }
