// Autogenerated from development/elements/analyzable.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface writeonly_analyzable extends writeonly_position, any_analyzable { }
