// Autogenerated from development/elements/action.i

package ideal.development.elements;

import ideal.library.elements.*;
import ideal.library.reflections.*;

public interface writeonly_action extends writeonly_analysis_result, writeonly_origin, any_action { }
