// Autogenerated from development/elements/construct.i

package ideal.development.elements;

import ideal.library.elements.*;

public interface writeonly_construct extends writeonly_data, writeonly_origin, any_construct { }
