// Autogenerated from development/comments/documentation.i

package ideal.development.comments;

import ideal.library.elements.*;
import ideal.library.texts.*;
import ideal.runtime.elements.*;

import javax.annotation.Nullable;

public interface documentation extends readonly_documentation, writeonly_documentation {
  @Nullable text_fragment section(documentation_section the_section);
}
