// Autogenerated from development/comments/documentation_section.i

package ideal.development.comments;

import ideal.library.elements.*;
import ideal.library.texts.*;
import ideal.runtime.elements.*;

public enum documentation_section implements enum_data {
  ALL,
  SUMMARY;
  public string to_string() {
    return new base_string(toString());
  }
}
