// Autogenerated from development/tests/all_tests.i

package ideal.development.tests;

import ideal.library.elements.*;
import ideal.development.names.*;
import ideal.development.futures.*;
import ideal.development.origins.*;
import ideal.development.documenters.*;

public class all_tests {
  public static void run_all_tests() {
    ideal.runtime.tests.all_tests.run_all_runtime_tests();
    all_tests.run_all_development_tests();
  }
  public static void run_all_development_tests() {
    new test_names().run_all_tests();
    new test_origin_printer().run_all_tests();
    new test_futures().run_all_tests();
    new test_doc_grammar().run_all_tests();
  }
}
