// Autogenerated from development/kinds/subtype_tags.i

package ideal.development.kinds;

import ideal.library.elements.*;
import ideal.runtime.elements.*;
import ideal.runtime.logs.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.flavors.*;

public class subtype_tags {
  public static final subtype_tag subtypes_tag = new base_subtype_tag(new base_string("subtypes"));
  public static final subtype_tag extends_tag = new base_subtype_tag(new base_string("extends"));
  public static final subtype_tag implements_tag = new base_subtype_tag(new base_string("implements"));
  public static final subtype_tag refines_tag = new base_subtype_tag(new base_string("refines"));
  public static final subtype_tag aliases_tag = new base_subtype_tag(new base_string("aliases"));
}
