// Autogenerated from runtime/patterns/validatable.i

package ideal.runtime.patterns;

import ideal.library.elements.*;
import ideal.library.patterns.*;
import ideal.runtime.elements.*;

public interface deeply_immutable_validatable extends deeply_immutable_value, immutable_validatable { }
