// Autogenerated from runtime/patterns/predicate_pattern.i

package ideal.runtime.patterns;

import ideal.library.elements.*;
import ideal.library.patterns.*;
import ideal.runtime.elements.*;

public class predicate_pattern<element_type> extends one_pattern<element_type> {
  public final function1<Boolean, element_type> the_predicate;
  public predicate_pattern(final function1<Boolean, element_type> the_predicate) {
    this.the_predicate = the_predicate;
  }
  public @Override boolean matches(final element_type the_element) {
    return this.the_predicate.call(the_element);
  }
}
