// Autogenerated from runtime/patterns/validatable.i

package ideal.runtime.patterns;

import ideal.library.elements.*;
import ideal.library.patterns.*;
import ideal.runtime.elements.*;

public interface readonly_validatable extends readonly_value, any_validatable { }
