// Autogenerated from runtime/patterns/repeat_element.i

package ideal.runtime.patterns;

import ideal.library.elements.*;
import ideal.library.patterns.*;
import ideal.runtime.elements.*;

public class repeat_element<element_type> extends base_repeat_element<element_type> {
  private final function1<Boolean, element_type> the_predicate;
  private final boolean do_match_empty;
  public repeat_element(final function1<Boolean, element_type> the_predicate, final boolean do_match_empty) {
    this.the_predicate = the_predicate;
    this.do_match_empty = do_match_empty;
  }
  public @Override boolean matches(final element_type the_element) {
    return this.the_predicate.call(the_element);
  }
  public @Override boolean match_empty() {
    return this.do_match_empty;
  }
}
