// Autogenerated from runtime/patterns/validatable.i

package ideal.runtime.patterns;

import ideal.library.elements.*;
import ideal.library.patterns.*;
import ideal.runtime.elements.*;

public interface validatable extends value, readonly_validatable, writeonly_validatable {
  void validate();
}
