// Autogenerated from runtime/formats/json_parser.i

package ideal.runtime.formats;

import ideal.library.elements.*;
import ideal.library.characters.*;
import ideal.runtime.elements.*;

import javax.annotation.Nullable;

public class json_parser {
  public final character_handler the_character_handler;
  public list<Object> tokens;
  public @Nullable string error;
  public json_parser(final character_handler the_character_handler) {
    this.the_character_handler = the_character_handler;
    this.tokens = new base_list<Object>();
  }
  public boolean has_error() {
    return this.error != null;
  }
  private void tokenize(final string input) {
    this.tokens.clear();
    int start = 0;
    while (start < input.size() && this.error == null) {
      start = this.scan(input, start);
    }
  }
  public list<Object> test_tokenize(final string input) {
    this.tokenize(input);
    assert !this.has_error();
    return this.tokens;
  }
  private int scan(final string input, int start) {
    final char next = input.get(start);
    start += 1;
    if (this.the_character_handler.is_whitespace(next)) {
      while (start < input.size() && this.the_character_handler.is_whitespace(input.get(start))) {
        start += 1;
      }
      return start;
    }
    if (next == '\"') {
      final int string_start = start;
      while (start < input.size()) {
        final char next_in_string = input.get(start);
        if (next_in_string == '\"') {
          this.tokens.append(input.slice(string_start, start));
          return start + 1;
        }
        start += 1;
      }
      this.report_error(new base_string("No closing quote in a string"));
      return start;
    }
    if (this.the_character_handler.is_digit(next)) {
      final @Nullable Integer digit = this.the_character_handler.from_digit(next, radix.DEFAULT_RADIX);
      assert digit >= 0;
      int result = digit;
      while (start < input.size() && this.the_character_handler.is_digit(input.get(start))) {
        final @Nullable Integer next_digit = this.the_character_handler.from_digit(input.get(start), radix.DEFAULT_RADIX);
        assert next_digit >= 0;
        result = result * radix.DEFAULT_RADIX + next_digit;
        start += 1;
      }
      this.tokens.append(result);
      return start;
    }
    if (next == json_token.OPEN_BRACE.token) {
      this.tokens.append(json_token.OPEN_BRACE);
      return start;
    }
    if (next == json_token.CLOSE_BRACE.token) {
      this.tokens.append(json_token.CLOSE_BRACE);
      return start;
    }
    if (next == json_token.OPEN_BRACKET.token) {
      this.tokens.append(json_token.OPEN_BRACKET);
      return start;
    }
    if (next == json_token.CLOSE_BRACKET.token) {
      this.tokens.append(json_token.CLOSE_BRACKET);
      return start;
    }
    if (next == json_token.COMMA.token) {
      this.tokens.append(json_token.COMMA);
      return start;
    }
    if (next == json_token.COLON.token) {
      this.tokens.append(json_token.COLON);
      return start;
    }
    this.report_error(ideal.machine.elements.runtime_util.concatenate(new base_string("Unrecognized character in a string: "), next));
    return start;
  }
  private void report_error(final string message) {
    this.error = message;
  }
}
