// Autogenerated from runtime/formats/json_object_impl.i

package ideal.runtime.formats;

import ideal.library.elements.*;
import ideal.library.characters.*;
import ideal.library.formats.*;
import ideal.runtime.elements.*;

public class json_object_impl extends hash_dictionary<string, Object> implements json_object {
  public json_object_impl() { }
}
