// Autogenerated from development/texts/text_event.i

package ideal.development.texts;

import ideal.library.elements.*;
import ideal.library.texts.*;
import ideal.runtime.elements.*;
import ideal.runtime.texts.*;

public interface text_event extends deeply_immutable_data, deeply_immutable_stringable { }
