// Autogenerated from development/jumps/jump_wrapper.i

package ideal.development.jumps;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.types.common_types;

public abstract class jump_wrapper implements entity_wrapper {
  public @Override type type_bound() {
    return common_types.unreachable_type();
  }
  public jump_wrapper() { }
}
