// Autogenerated from development/jumps/returned_value.i

package ideal.development.jumps;

import ideal.library.elements.*;
import ideal.library.reflections.*;
import ideal.runtime.elements.*;
import ideal.development.elements.*;
import ideal.development.names.*;
import ideal.development.types.common_types;

public class returned_value extends jump_wrapper {
  public final entity_wrapper result;
  public returned_value(final entity_wrapper result) {
    this.result = result;
  }
  public @Override string to_string() {
    return ideal.machine.elements.runtime_util.concatenate(new base_string("return value: "), this.result);
  }
}
