// Autogenerated from development/futures/operation.i

package ideal.development.futures;

import ideal.library.elements.*;
import ideal.runtime.elements.*;

public interface any_operation extends any_data, any_stringable { }
