// Autogenerated from development/futures/future.i

package ideal.development.futures;

import ideal.library.elements.*;
import ideal.runtime.elements.*;

public interface deeply_immutable_future<element> extends immutable_future<element> { }
