// Autogenerated from development/futures/lifespan.i

package ideal.development.futures;

import ideal.library.elements.*;
import ideal.runtime.elements.*;

public interface deeply_immutable_lifespan extends deeply_immutable_disposable, immutable_lifespan { }
