// Autogenerated from development/futures/operation.i

package ideal.development.futures;

import ideal.library.elements.*;
import ideal.runtime.elements.*;

public interface deeply_immutable_operation extends deeply_immutable_data, deeply_immutable_stringable, immutable_operation { }
