// Autogenerated from development/futures/event_queue.i

package ideal.development.futures;

import ideal.library.elements.*;
import ideal.runtime.elements.*;

public class event_queue {
  public static final list<base_operation> pending = new base_list<base_operation>();
  public static boolean is_empty() {
    return event_queue.pending.is_empty();
  }
  public static void schedule(final base_operation the_operation) {
    event_queue.pending.append(the_operation);
  }
  public static void process() {
    while (!event_queue.is_empty()) {
      final base_operation next = event_queue.pending.remove_at(0);
      next.execute();
    }
  }
}
