// Autogenerated from development/futures/lifespan.i

package ideal.development.futures;

import ideal.library.elements.*;
import ideal.runtime.elements.*;

public interface lifespan extends disposable, readonly_lifespan, writeonly_lifespan {
  void add_resource(disposable resource);
  lifespan sub_span();
}
