// Autogenerated from development/futures/disposable.i

package ideal.development.futures;

import ideal.library.elements.*;
import ideal.runtime.elements.*;

public interface readonly_disposable extends any_disposable { }
