// Autogenerated from development/futures/future.i

package ideal.development.futures;

import ideal.library.elements.*;
import ideal.runtime.elements.*;

import javax.annotation.Nullable;

public interface readonly_future<element> extends readonly_value, any_future<element> {
  boolean is_done();
  @Nullable element value();
}
