// Autogenerated from development/futures/operation.i

package ideal.development.futures;

import ideal.library.elements.*;
import ideal.runtime.elements.*;

public interface writeonly_operation extends writeonly_data, writeonly_stringable, any_operation { }
