// Autogenerated from development/futures/future.i

package ideal.development.futures;

import ideal.library.elements.*;
import ideal.runtime.elements.*;

public interface writeonly_future<element> extends any_future<element> { }
